// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['utils']['Calculator']['Add'](arg1, arg2);
}
